### ISSUE TITLE
文字の大きさを項目の用途に応じて調整する

### ISSUE THREAD

**Issue by takagram** [takagram/iniad-fake-homepage-a5#5]

**Comment by iida-yoshio** [comment]
文字の大きさのバランスを直してみます。
よろしくお願いします。

**Comment by iida-yoshio** [comment]
日時と場所の文字の大きさを変更するため、index.htmlの方に、id属性(id="date-place")を追加しました。
その後、commit と pushを実施しました。
よろしくお願いします。

**Comment by takagram** [comment]
飯田さん、課題としての完了状態は↓の「Close with comment」をクリックして、状態を「closed」にすることのようなので、後ほどお願いいたします！

**Comment by iida-yoshio** [comment]
ありがとうございました。
